export default {
  login: "Skyy-Banerjee",
  id: 51888502,
  node_id: "MDQ6VXNlcjUxODg4NTAy",
  avatar_url: "https://avatars.githubusercontent.com/u/51888502?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Skyy-Banerjee",
  html_url: "https://github.com/Skyy-Banerjee",
  followers_url: "https://api.github.com/users/Skyy-Banerjee/followers",
  following_url:
    "https://api.github.com/users/Skyy-Banerjee/following{/other_user}",
  gists_url: "https://api.github.com/users/Skyy-Banerjee/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Skyy-Banerjee/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Skyy-Banerjee/subscriptions",
  organizations_url: "https://api.github.com/users/Skyy-Banerjee/orgs",
  repos_url: "https://api.github.com/users/Skyy-Banerjee/repos",
  events_url: "https://api.github.com/users/Skyy-Banerjee/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Skyy-Banerjee/received_events",
  type: "User",
  site_admin: false,
  name: "Soumadip Banerjee",
  company: null,
  blog: "",
  location: "Kolkata",
  email: null,
  hireable: null,
  bio: "Software engineer⚛️, tech enthusiast👨🏻‍💻, musician🎸, horror-novel fanatic🧛🏻‍♂️",
  twitter_username: null,
  public_repos: 67,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-06-16T18:59:12Z",
  updated_at: "2024-08-12T15:22:18Z",
};
